id: A1E63816C
title: A Heart Prayer to Orgyen Dorje Chang
type: translation
pechas:
- IE99921FF
- I72C72DE2
- ID9A0BC6C
- I5495D495
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:10:56.107840
  last_modified_at: 2023-01-04 12:10:56.107850
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IE99921FF/0930: 9E2C
  I72C72DE2/33AE: 9E2C
  ID9A0BC6C/42F7: 9E2C
  I5495D495/4657: 9E2C
